### ISSUE TITLE
Create usecase diagram, functional requirement

### ISSUE THREAD

**Issue by BurusB** [norbi9909/afp2-inventory#1]
Create the following:
- [x] Usecase diagram
- [x] Functional requirement

**Comment by norbi9909** [comment]
Usecase diagram is read, waiting for approval.

**Comment by Atrombix** [comment]
Usecase diagram is done, waiting for accept.

**Comment by Bazsa47** [comment]
reviewed func. spec. Changed stuff, needs review again
